name: CI/CD

on:
  push:

jobs:

  build:
    name: Build
    uses: ./.github/workflows/01-build.yml
  
  release:
    name: Release
    if: ${{ contains(fromJSON('["main", "alpha", "beta"]'), github.ref_name) }}
    needs:
      - build
    uses: StudioLE/Actions/.github/workflows/01-semantic-release.yml@main
    secrets: inherit
  
  publish:
    name: Publish
    if: ${{ needs.release.outputs.version != '0.0.0' }}
    needs:
      - release
    uses: ./.github/workflows/03-publish.yml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
